//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedwireMessage.FrbCodes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FedwireMessage.FrbCodes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BTR&quot;: &quot;Bank Transfer (Beneficiary is a bank)&quot;,
        ///    &quot;DRC&quot;: &quot;Customer or Corporate Drawdown Request&quot;,
        ///    &quot;CKS&quot;: &quot;Check Same Day Settlement&quot;,
        ///    &quot;DRW&quot;: &quot;Drawdown Payment&quot;,
        ///    &quot;CTP&quot;: &quot;Customer Transfer Plus&quot;,
        ///    &quot;FFR&quot;: &quot;Fed Funds Returned&quot;,
        ///    &quot;CTR&quot;: &quot;Customer Transfer (Beneficiary is a not a bank)&quot;,
        ///    &quot;FFS&quot;: &quot;Fed Funds Sold&quot;,
        ///    &quot;DEP&quot;: &quot;Deposit to Sender’s Account&quot;,
        ///    &quot;SVC&quot;: &quot;Service Message&quot;,
        ///    &quot;DRB&quot;: &quot;Bank-to-Bank Drawdown Request&quot;
        ///}.
        /// </summary>
        internal static string BusinessFunctionCode {
            get {
                return ResourceManager.GetString("BusinessFunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;B&quot;: &quot;SWIFT Bank Identifier Code (BIC)&quot;,
        ///    &quot;C&quot;: &quot;CHIPS Participant&quot;,
        ///    &quot;D&quot;: &quot;Demand Deposit Account (DDA) Number&quot;,
        ///    &quot;F&quot;: &quot;Fed Routing Number&quot;,
        ///    &quot;T&quot;: &quot;SWIFT BIC or Bank Entity Identifier (BEI) and account number&quot;,
        ///    &quot;U&quot;: &quot;CHIPS Identifier&quot;,
        ///    &quot;1&quot;: &quot;Passport Number&quot;,
        ///    &quot;2&quot;: &quot;Tax Identification Number&quot;,
        ///    &quot;3&quot;: &quot;Driver’s License Number&quot;,
        ///    &quot;4&quot;: &quot;Alien Registration Number&quot;,
        ///    &quot;5&quot;: &quot;Corporate Identification&quot;,
        ///    &quot;9&quot;: &quot;Other Identification&quot;
        ///}
        ///.
        /// </summary>
        internal static string IdCodes {
            get {
                return ResourceManager.GetString("IdCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { 
        ///    &quot;00&quot;: &quot;Basic Funds Transfer&quot;,
        ///    &quot;01&quot;: &quot;Request for Reversal&quot;,
        ///    &quot;02&quot;: &quot;Reversal of Transfer&quot;,
        ///    &quot;07&quot;: &quot;Request for Reversal of a Prior Day Transfer&quot;,
        ///    &quot;08&quot;: &quot;Reversal of a Prior Day Transfer&quot;,
        ///    &quot;31&quot;: &quot;Request for Credit (Drawdown)&quot;,
        ///    &quot;32&quot;: &quot;Funds Transfer Honoring a Request for Credit (Drawdown)&quot;,
        ///    &quot;33&quot;: &quot;Refusal to Honor a Request for Credit (Drawdown)&quot;,
        ///    &quot;90&quot;: &quot;Service Message&quot;
        ///}
        ///.
        /// </summary>
        internal static string SubTypeCode {
            get {
                return ResourceManager.GetString("SubTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;10&quot;: &quot;Funds Transfer&quot;,
        ///    &quot;15&quot;: &quot;Foreign Transfer&quot;,
        ///    &quot;16&quot;: &quot;Settlement Transfer&quot;
        ///}
        ///.
        /// </summary>
        internal static string TypeCode {
            get {
                return ResourceManager.GetString("TypeCode", resourceCulture);
            }
        }
    }
}
